export type SoundId =
  | 'itemDrop'
  | 'itemGrab'
  | 'spawn'
  | 'lock'
  | 'unlock'
  | 'spaceEnter'
  | 'spaceExit'
  | 'menuOpen'
  | 'menuClose'
  | 'undo'
  | 'redo'
  | 'delete'
  | 'modalOpen'
  | 'themeToLight'
  | 'themeToDark'
